@startuml

class ShipCaptain{

}

class User{
    -String id <<b>PK>
    -String password
    -UserRole role
}

class UserRole{
    -String id <<b>PK>
    -String description
}

class GetOccupancyRateCargoManifestUI(){

}

class GetOccupancyRateCargoManifestController(){

}

class Company {
    -TreeofShips treeOfShips
}

class TreeofShips{

}

class CargoManifest{
    HashMap<Container, int>
}

class Ship {

    -int MMSI <<b>PK>
    -String name
    -int IMO
    -int numberEnergyGenerator
    -int powerOutput
    -String callSign
    -int vesselType
    -double length
    -double width
    -int maximumCapacity
    -double draft
}

class Container {

    -String containerID <<b>PK>
    -int checkDigit
    -String ISO
    -int gross
    -int tare
    -int payload
    -int maxVolume
    -int repairRecommendation

}

@enduml