@startuml

autonumber

actor ShipCaptian #red


System --> ShipCaptian: Authentication Request
ShipCaptian -> System : Another authentication Response
System --> ShipCaptian : Authentication successful
ShipCaptian --> ShipCaptianUI : Asks for the occupancy rate (percentage) of a given ship for a given cargo manifest
ShipCaptianUI --> GetOccupancyRateCargoManifestUI : access
GetOccupancyRateCargoManifestUI --> ShipCaptian : Asks for the Ship MMSI or CallSign
ShipCaptian --> GetOccupancyRateCargoManifestUI : Inserts the data
GetOccupancyRateCargoManifestUI --> GetOccupancyRateCargoManifestController : getOccupancyRateCargoManifestController()
database       "DataBase"              as db
GetOccupancyRateCargoManifestController -> db** : getOccupancyRateCargoManifestController()
GetOccupancyRateCargoManifestController --> GetOccupancyRateCargoManifestUI : result
GetOccupancyRateCargoManifestUI --> ShipCaptian : Shows the occupancy rate (percentage) of a given ship for a given cargo manifest

@enduml