@startuml

class RequestTemporallyPositions{

}

class RequestTemporallyPositionsController{

}

class RequestTemporallyPositionsUI{

}

class Ship {
    -int MMSI <<b>PK>
    -String name
    -int IMO
    -int numberEnergyGenerator
    -int powerOutput
    -String callSign
    -int vesselType
    -double length
    -double width
    -int maximumCapacity
    -double draft
}

class PositionData{
    Date baseDateTime;
    double latitude;
    double longitude;
    double sog;
    double cog;
    double heading;
    int position;
}

class Company {

}

RequestTemporallyPositions <--> RequestTemporallyPositionsController
RequestTemporallyPositionsController <--> RequestTemporallyPositionsUI
RequestTemporallyPositionsUI <--> Company
Company *-- Ship
PositionData *-- Ship

@enduml