@startuml
'https://plantuml.com/sequence-diagram

autonumber

TrafficManager -> System :  I wish to know the shortest path between two locals (city and/or port).
System --> TrafficManager: Asks which one of the paths
TrafficManager -> System : Confirms
System --> TrafficManager : Displays the shortest path

@enduml