@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor       ShipCaptain                as SC
participant    ":getListContainerToBeLoadedUI"         as ui
participant    ":getListContainerToBeLoadedController" as ctrl
participant    ":Company"                 as company
database       "DataBase"              as db

SC -> ui : List of containers to be offloaded in the next port

activate ui

    ui -> ctrl : getListContainerToBeLoaded()

    activate ctrl

    ctrl -> company : getListContainerToBeLoaded()

    activate company

    company -> db** : getShipsListContainerToBeLoaded()

    company -> db : getPortsListContainerToBeLoaded()

    company -> company : getListContainerToBeLoaded()

    deactivate company

    deactivate ctrl


ui --> SC : listContainers

deactivate ui
@enduml