@startuml
'https://plantuml.com/sequence-diagram

autonumber

skinparam sequenceMessageAlign center

System -> ShipCaptain: Authentication Request
ShipCaptain --> System: Authentication Response

System -> ShipCaptain: Operation Request
System <-- ShipCaptain: List of containers to be loaded in the next port

System -> ShipCaptain: Shows the containers list
System <-- ShipCaptain: Confirms the operation

System -> ShipCaptain: Operation completed
@enduml