@startuml
autonumber

actor PortStaff #red

System --> PortStaff: Authentication Request
PortStaff -> System : Another authentication Response
System --> PortStaff : Authentication successful
PortStaff --> System : Wish to fill a statically reserved matrix in memory with each container's ID in its respective place.
System --> PortStaff : Asks for the Cargo Manifest ID
PortStaff --> System : Inserts the Cargo Manifest ID
System --> PortStaff : Warns of the successful/unsuccessful of the task

@enduml