@startuml

class Container {

    -String containerID <<b>PK>
    -int checkDigit
    -String ISO
    -int gross
    -int tare
    -int payload
    -int maxVolume
    -int repairRecommendation

}

class Client{

}

class User{

}

class UserRole{

}

class GetInfoContainerUI{

}

class GetInfoContainerController{

}

@enduml