@startuml

autonumber

actor       TrafficManager                as TM
participant    ":getShipDetailUI"         as UI
participant    ":getShipDetailController" as CTRL
participant    ":Company"                 as company
box "Optional (it depends of the code used as parameter)" #LightBlue
participant    ":TreeOfShips_MMSI"        as mmsi
participant    ":TreeOfShips_IMO"         as imo
participant    ":TreeOfShips_CallSign"    as callSign
end box

TM -> UI : Search details of a ship
activate UI
UI --> TM: Request any of ship code (MMSI, IMO or Call Sign)
deactivate UI

TM -> UI : Insert ship code
activate UI

    UI -> CTRL : getShipByCode(code)
    activate CTRL
    CTRL -> company : ship = getShipByCode(code)
    activate company



    company -> mmsi : ship = getShipByMMSI(code)
    activate mmsi
    deactivate mmsi

    company -> imo : ship = getShipByIMO(code)
    activate imo
    deactivate imo

    company -> callSign : ship = getShipByCallSign(code)
    activate callSign
    deactivate callSign


    deactivate company

    deactivate CTRL

UI --> TM : ship
deactivate UI

@enduml
