@startuml

autonumber

actor ShipCaptain #red

System --> ShipCaptain: Authentication Request
ShipCaptain -> System : Another authentication Response
System --> ShipCaptain : Authentication successful
ShipCaptain --> ShipCaptainUI : Asks to know the number of days each ship has been idle since the beginning of the current year.
ShipCaptainUI --> ShowCenterGravityLoadedUI : Connects
ShowCenterGravityLoadedUI --> GetShipByCodeController : MMSI
GetShipByCodeController --> Company : getShipByCode()
Company --> GetShipByCodeController : ship
GetShipByCodeController --> ShowCenterGravityLoadedUI : ship
ShowCenterGravityLoadedUI --> ShowCenterGravityLoadedController : containerImportController(filename, ship)
ShowCenterGravityLoadedController --> Company : containerImportController(filename, ship)
ShowCenterGravityLoadedUI --> ShowCenterGravityLoadedController : allocatingContainersController(ship);
ShowCenterGravityLoadedController --> Company : allocatingContainersController(ship);
Company --> ShowCenterGravityLoadedController : Map<Integer, double[][]> mapAllocatted
ShowCenterGravityLoadedController --> ShowCenterGravityLoadedUI : Map<Integer, double[][]> mapAllocatted
ShowCenterGravityLoadedUI --> ShowCenterGravityLoadedController : showCenterOfGravityController(ship, mapAllocatted);
ShowCenterGravityLoadedController --> Company : showCenterOfGravityController(ship, mapAllocatted);
Company --> ShowCenterGravityLoadedUI : Shows everything
ShowCenterGravityLoadedUI --> ShipCaptain : Delivers the information asked

@enduml