@startuml
'https://plantuml.com/class-diagram

class ShipCaptain{
}

class Company {

}

class Ship {
    -int MMSI <<b>PK>
    -String name
    -int IMO
    -int numberEnergyGenerator
    -int powerOutput
    -String callSign
    -int vesselType
    -double length
    -double width
    -int maximumCapacity
    -double draft
}

ShipCaptain -> Company
Company -> Ship




@enduml