@startuml

autonumber

actor ShipChiefElectricalEngineer #red

System --> ShipChiefElectricalEngineer: Authentication Request
ShipChiefElectricalEngineer -> System : Another authentication Response
System --> ShipChiefElectricalEngineer : Authentication successful
ShipChiefElectricalEngineer --> ShipChiefElectricalEngineerUI : Asks for the set of materials to use in a container, to operate at temperatures of 7°C.
ShipChiefElectricalEngineerUI --> GetSetOfMaterialsToContainerAtSevenUI : Connects
GetSetOfMaterialsToContainerAtSevenUI --> GetSetOfMaterialsToContainerAtSevenController : asks for the info
database       "DataBase"              as db
GetSetOfMaterialsToContainerAtSevenController --> db** : getInfoContainerController(answer)
db --> GetSetOfMaterialsToContainerAtSevenController : List<String>
GetSetOfMaterialsToContainerAtSevenController --> GetSetOfMaterialsToContainerAtSevenUI : List<String>
GetSetOfMaterialsToContainerAtSevenUI --> ShipChiefElectricalEngineer : Delivers the information asked

@enduml