@startuml

autonumber

actor PortStaff #red

System --> PortStaff: Authentication Request
PortStaff -> System : Another authentication Response
System --> PortStaff : Authentication successful
PortStaff --> PortStaffUI : Asks for the total number of occupied slots on the Port.
PortStaffUI --> GetTotalNumberOfOccupiedSlotsUI : Connects
GetTotalNumberOfOccupiedSlotsUI --> GetTotalNumberOfOccupiedSlotsController : asks for the info
database       "DataBase"              as db
GetTotalNumberOfOccupiedSlotsController --> db** : getTotalNumberOfOccupiedSlotsController()
db --> GetTotalNumberOfOccupiedSlotsController : result
GetTotalNumberOfOccupiedSlotsController --> GetTotalNumberOfOccupiedSlotsUI : result
GetTotalNumberOfOccupiedSlotsUI --> PortStaff : Delivers the information asked

@enduml