@startuml
autonumber

actor PortStaff #red

System --> PortStaff: Authentication Request
PortStaff -> System : Another authentication Response
System --> PortStaff : Authentication successful
PortStaff --> System : Asks for the total number of occupied slots on the Port.
System --> PortStaff : Delivers the information asked

@enduml