@startuml

autonumber

actor       TrafficManager                as tm
participant    ":getListShipsAvailableMondayNextWeekUI"         as ui
participant    ":getListShipsAvailableMondayNextWeekController" as ctrl
database       "DataBase"              as db

tm -> ui : List of ships will be available on Monday next week

activate ui

    ui -> ctrl : getListShipsAvailableMondayNextWeek()

    activate ctrl

    ctrl -> db** : getListShipsAvailableMondayNextWeek()

    deactivate ctrl


ui --> tm : listShips

deactivate ui

@enduml