@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor       TrafficManager             as TM
participant    ":ClosestPortUI"         as UI
participant    ":ClosestPortController" as CTRL
participant    ":Company"              as Company
participant    ":TreeOfPorts"   as TreeOfPorts
participant    ":treeOfShipsCallSign"   as treeOfShipsCallSign
participant    ":treeOfPositionData"   as TreeOfPositionData
participant    ":KD:TREE"   as KD
database       "DataBase"              as db

TM -> UI : , I wish to find the closest port of a ship given its CallSign \n on a certain DateTime.
activate UI
UI --> TM: Requests the Call Sign and the date
deactivate UI

TM -> UI : Enters the requested data
activate UI

UI -> CTRL : getClosest(...)
activate CTRL
CTRL -> Company : getClosest(..)
activate Company
Company -> Company : getPositionDataByCallSignAndDateTime(...)
Company -> db** : getShipByCallSign(...)
Company -> db : closestData(...)
Company -> db : getClosest(...)
Company -> CTRL : ClosestPort
deactivate Company
CTRL -> UI : ClosestPort
UI -> TM : Prints the closest Port name

@enduml