@startuml

autonumber

actor ShipChiefElectricalEngineer #red

System --> ShipChiefElectricalEngineer: Authentication Request
ShipChiefElectricalEngineer -> System : Another authentication Response
System --> ShipChiefElectricalEngineer : Authentication successful
ShipChiefElectricalEngineer --> System : Asks for the summary document about materials and thermal resistances about refrigerated containers.
ShipChiefElectricalEngineerUI --> GetSummaryDocumentMaterialsUI : Connects
GetSummaryDocumentMaterialsUI --> GetSummaryDocumentMaterialsController : asks for the info
database       "DataBase"              as db
GetSummaryDocumentMaterialsController --> db** : getSummaryDocumentMaterialsController()
db --> GetSummaryDocumentMaterialsController : List<String>
GetSummaryDocumentMaterialsController --> GetSummaryDocumentMaterialsUI : List<String>
GetSummaryDocumentMaterialsUI --> ShipChiefElectricalEngineer : Delivers the summary document

@enduml