@startuml
autonumber

actor ShipChiefElectricalEngineer #red

System --> ShipChiefElectricalEngineer: Authentication Request
ShipChiefElectricalEngineer -> System : Another authentication Response
System --> ShipChiefElectricalEngineer : Authentication successful
ShipChiefElectricalEngineer --> System : Asks for the summary document about materials and thermal resistances about refrigerated containers.
System --> ShipChiefElectricalEngineer : Delivers the summary document

@enduml