@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam sequenceMessageAlign center

TrafficManager -> System: Authentication Request
System --> TrafficManager: Authentication Response

TrafficManager -> System: Build a freight network
TrafficManager <-- System: ask for files pathes

TrafficManager -> System: Inserts files pathes
TrafficManager <-- System: Generates freight network and informs about the success of the operation.
@enduml